name: Test

on: push

jobs:
  first-job:
    name: Say hi
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: echo Hi from our first worlflow!
    
    - name: Show ASCII greeting
      uses: mscoutermarsh/ascii-art-action@master
      with:
        text: 'HELLO!'